# Generated by Django 3.2 on 2023-10-13 10:28

from django.db import migrations, models
import products.models


class Migration(migrations.Migration):

    dependencies = [
        ('products', '0002_offer'),
    ]

    operations = [
        migrations.AlterField(
            model_name='product',
            name='file_image_url',
            field=models.ImageField(upload_to=products.models.product_directory_path),
        ),
    ]
