# Generated by Django 3.2 on 2023-10-13 10:38

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('products', '0003_alter_product_file_image_url'),
    ]

    operations = [
        migrations.AlterField(
            model_name='product',
            name='date_add',
            field=models.DateField(),
        ),
        migrations.AlterField(
            model_name='product',
            name='date_end',
            field=models.DateField(),
        ),
    ]
