# Generated by Django 3.2 on 2023-10-19 14:44

from django.db import migrations, models
import products.models


class Migration(migrations.Migration):

    dependencies = [
        ('products', '0003_alter_product_file_image_url'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='offer',
            options={'verbose_name': 'Discount', 'verbose_name_plural': 'Discounts'},
        ),
        migrations.AlterModelOptions(
            name='product',
            options={'verbose_name': 'Florarium', 'verbose_name_plural': 'Florariums'},
        ),
        migrations.AlterField(
            model_name='offer',
            name='code',
            field=models.CharField(max_length=10, verbose_name='Promo'),
        ),
        migrations.AlterField(
            model_name='offer',
            name='description',
            field=models.CharField(max_length=255, verbose_name='Description'),
        ),
        migrations.AlterField(
            model_name='offer',
            name='discount',
            field=models.FloatField(verbose_name='Size in %'),
        ),
        migrations.AlterField(
            model_name='product',
            name='desc',
            field=models.TextField(max_length=2083, verbose_name='Description'),
        ),
        migrations.AlterField(
            model_name='product',
            name='file_image_url',
            field=models.ImageField(upload_to=products.models.product_directory_path, verbose_name='Image'),
        ),
        migrations.AlterField(
            model_name='product',
            name='id',
            field=models.IntegerField(primary_key=True, serialize=False),
        ),
        migrations.AlterField(
            model_name='product',
            name='name',
            field=models.CharField(max_length=255, verbose_name='Name'),
        ),
        migrations.AlterField(
            model_name='product',
            name='price',
            field=models.FloatField(verbose_name='Price'),
        ),
        migrations.AlterField(
            model_name='product',
            name='stock',
            field=models.IntegerField(verbose_name='Count'),
        ),
    ]
