# Generated by Django 3.2 on 2023-10-25 06:08

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('products', '0004_auto_20231019_1744'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='product',
            options={'ordering': ['date_add'], 'verbose_name': 'Florarium', 'verbose_name_plural': 'Florariums'},
        ),
        migrations.AlterField(
            model_name='product',
            name='date_add',
            field=models.DateTimeField(auto_now=True, verbose_name='Date add'),
        ),
        migrations.AlterField(
            model_name='product',
            name='date_end',
            field=models.DateTimeField(verbose_name='Date off'),
        ),
    ]
