# Generated by Django 3.2 on 2023-10-27 07:26

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('products', '0007_auto_20231027_1022'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='gallery',
            options={'verbose_name': 'Image', 'verbose_name_plural': 'Images'},
        ),
    ]
